name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install
      run: npm install

    - name: build
      run: npm run build

    - name: lint
      run: npm run lint

    - name: test
      run: npm test
