name: Release publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Uses NodeJS 12x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@iuriioapps'
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - run: npm test
      env:
        CI: true
    - run: npm run gh-pages
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
